conf backup aws

diff --git a/.github/workflows/backup.yml b/.github/workflows/backup.yml
--- a/.github/workflows/backup.yml
+++ b/.github/workflows/backup.yml
@@ -3,9 +3,8 @@ name: Database Backup
 on:
   schedule:
     - cron: '0 2 * * *' # Programado para ejecutarse todos los días a las 2 AM UTC
-
   workflow_dispatch:
-  
+
 jobs:
   backup:
     runs-on: ubuntu-latest
@@ -15,12 +14,20 @@ jobs:
         run: |
           sudo rm -rf /usr/local/aws-cli
 
+      - name: Install unzip
+        run: sudo apt-get install -y unzip
+
       - name: Install AWS CLI
         run: |
-          curl "https://awscli.amazonaws.com/AWSCLIV2.zip" -o "AWSCLIV2.zip"
-          unzip AWSCLIV2.zip
-          sudo ./aws/install --update
-
+          curl -O https://awscli.amazonaws.com/AWSCLIV2.zip
+          if [ -f AWSCLIV2.zip ]; then
+            echo "Download successful, proceeding to unzip..."
+            unzip AWSCLIV2.zip
+            sudo ./aws/install --update
+          else
+            echo "Download failed!"
+            exit 1
+          fi
       
       - name: Backup Database
         env:
@@ -38,3 +45,4 @@ jobs:
           S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
         run: |
           aws s3 cp backup.sql s3://$S3_BUCKET_NAME/backup_$(date +'%Y%m%d').sql
+
